### ISSUE TITLE
Doesn't respect display aspect ratio

### ISSUE THREAD

**Issue by cassidyjames** [elementary/videos#108]
If a video file has Display Aspect Ratio (DAR) metadata set—i.e. an anamorphic video shot on a 16:9 sensor—Videos does not properly scale the output to the correct ratio. This results in squeezed footage. VLC, for example, reads this data and de-squeezes the file for playback.

**Comment by davidmhewitt** [comment]
I've just been investigating this as I've just found the same issue. It appears to be caused by ClutterGst, I've raised an issue upstream here:
https://gitlab.gnome.org/GNOME/clutter-gst/issues/6

**Comment by selwynorren** [comment]
Hey All,

I still seem to be having this issue. Is there something I am missing here or something I need to install?

**Comment by mroi** [comment]
The aspect ratio for previously problematic videos is now correct in the current Flatpak release (version 3.0.0). Has this been fixed?

**Comment by danirabbit** [comment]
Most likely since we're no longer using clutter 🎉 

Closing as fixed :)
