### ISSUE TITLE
Video player displaying green screen

### ISSUE THREAD

**Issue by dwisatriow** [elementary/videos#115]
I just trying to open mp4 video in elementary os juno's video player, but it just showing green screen with the audio. I've check "install media codec" while installing the system. And when i try to play the video in the vlc, nothing error. Any work around to solve it?

**Comment by Dirli** [comment]
I had a similar problem when installing gstreamer-vaapi plugin

**Comment by danirabbit** [comment]
Closing since this is a very old report and the codec situation is very different these days
