### ISSUE TITLE
Not properly running flv formatted videos

### ISSUE THREAD

**Issue by TechRage** [elementary/videos#117]
Every time I try to run a new flv formatted video that I made from OBS Studio, Videos doesn't seem to pick run the video at all. I get a black screen with no time stamps, yet the bottom timeline bar appears, just not in the screenshot I took. The screen just stays blank and I've tried running it a few times. Could it be that it just doesn't support flv?

I ran the video with VLC and it worked without a problem.

![screenshot from 2019-02-02 23 25 53](https://user-images.githubusercontent.com/26153370/52172640-e895ce00-2741-11e9-93e3-78715b6afba3.png)

**Comment by arshubham** [comment]
Installing `gstreamer1.0-plugins-bad` fixes this.

**Comment by danirabbit** [comment]
Closing because flv videos recorded from OBS seem to be playing these days
