### ISSUE TITLE
space bar closes app

### ISSUE THREAD

**Issue by bksubhuti** [elementary/videos#127]
The space bar closes the app.  This is confusing because the space bar is  standard to pause the playback for most or major video players. (vlc and youtube and many others).

**Comment by worldofpeace** [comment]
This is not the behavior of this application.

Can you run `io.elementary.videos` in a terminal and see if any messages get outputted when you do this?

**Comment by bksubhuti** [comment]
io.elementary.videos

** (io.elementary.videos:3137): WARNING **: 20:55:57.045: Inhibitor.vala:62: Could not inhibit screen: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
Segmentation fault

using acer r11 2015 model.  32gb emc hard drive.  upgraded to 8gb ram

**Comment by worldofpeace** [comment]
`org.freedesktop.ScreenSaver` should exist from `lightlocker` in elementary.
Is it running?

**Comment by bksubhuti** [comment]
This might have been my fault.  I followed the instructions without reading
the whole thing here.

https://www.reddit.com/r/elementaryos/comments/9q31yq/kde_connect_on_eos_juno/

It did not work (which was the reply I did not read).  I did this by
installing the deb over here
https://github.com/mdh34/elementary-indicators

and that might be why I have this bug.  I selected to downgrade a the panel
and then it upgraded the next time I upgraded.  I deleted kde connect and
thought all was back to normal and that indicator apps were not possible.

can you look at the deb and  tell me what is needed to make things back to
normal?
I hope I don't need to reinstall the os again.

I'm not sure why I cannot use indicator apps like cpufreq and caffeine.






https://AmericanMonk.org

**Comment by peteruithoven** [comment]
Looks like this isn't an issue for Videos. 

> I'm not sure why I cannot use indicator apps like cpufreq and caffeine.

Please check any communication channel, it has been asked before.

**Comment by bksubhuti** [comment]
I reinstalled eOS and I can confirm that it works fine now (on my machine).
