### ISSUE TITLE
Native Video app does not play mpg files from a VCD

### ISSUE THREAD

**Issue by JigneshAngadia** [elementary/videos#131]
I have a VCD with mpg files that the native Videos app does not play the video, it just shows blank screen, and no audio either. VLC player plays the same files successfully. I do see gstreamer1.0-plugins-* are installed with version 1.14.5, as these were listed as a solution in another similar question about native Video app not able to play video files that VLC player plays successfully.

Please let me know if further clarification/information on this topic is needed from my side that could help addressing this issue at hand.

This issue was created as suggested in the comment to my question listed below, and none of the related issues listed pertain to this particular issue:
https://elementaryos.stackexchange.com/q/19663/18886

**Comment by arshubham** [comment]
@JigneshAngadia Can you check if Celluloid plays it? Please also share the codec info for the file you are trying to play in VLC (`Ctrl + J`)

**Comment by Angadia** [comment]
@arshubham 
a) I checked with the GNOME MPV (as Celluloid is not listed in the AppCentre), which is a non-curated media player but listed in the AppCentre, and it is not able to play it. The version for GNOME MPV is 0.13.
Do let me know if you need me to test it with Celluloid available at https://github.com/celluloid-player/celluloid

b) Codec info for the video that VLC media player displays is captured in the below listed screenshot: 
![Screenshot from 2020-07-03 13 48 37](https://user-images.githubusercontent.com/55114410/86496908-2c747480-bd34-11ea-910a-70c22e55d9a0.png)

**Comment by JigneshAngadia** [comment]
@arshubham
a) I checked with the GNOME MPV (as Celluloid is not listed in the AppCentre), which is a non-curated media player but listed in the AppCentre, and it is not able to play it. The version for GNOME MPV is 0.13.
Do let me know if you need me to test it with Celluloid available at https://github.com/celluloid-player/celluloid

b) Codec info for the video that VLC media player displays is captured in the below listed screenshot:
![Screenshot from 2020-07-03 13 48 37](https://user-images.githubusercontent.com/42557336/86498266-f2a66c80-bd39-11ea-9377-a952b94e81cf.png)
