### ISSUE TITLE
It stuck when playing video but audio continues (Ubuntu 18.04)

### ISSUE THREAD

**Issue by chandra-deb** [elementary/videos#138]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by arshubham** [comment]
@chandra-deb Please share additional details like a sample video file which is affected and if it is working in another video player. It would be impossible to debug without that.
