### ISSUE TITLE
Videos stops working and sticks.

### ISSUE THREAD

**Issue by kmalkenneth** [elementary/videos#167]
When you play a video and do simple actions such as pause or change the focus to another sale, it stops playing and sticks.

![Captura realizada el 2019-12-12 09 45 53](https://user-images.githubusercontent.com/26829105/70726986-88a67700-1cc4-11ea-8aea-05576d377c82.png)

It happens very often.

elementary OS 5.1 Hera
Linux 4.15.0-72-generic
Quad-Core AMD Ryzen 5 2400G with Radeon Vega Graphics
Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c6)
15,4 GB de memory
103,3 GB de storage (SATA SSD)

**Comment by danirabbit** [comment]
Closing since this is a quite old issue report and can't be reproduced
