### ISSUE TITLE
Videos are very choppy

### ISSUE THREAD

**Issue by Xvatten** [elementary/videos#168]
When watching mp4 videos the player is choppy and unresponsive.

Videos should not be choppy and the player should not be unresponsive.

This is shown when playing video from terminal:
```
$ /usr/bin/io.elementary.videos 
mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the -global-isel-abort option: may only occur zero or one times!
```

When closing the application window:
```
(io.elementary.videos:22674): GLib-GObject-WARNING **: 11:24:20.029: instance with invalid (NULL) class pointer

(io.elementary.videos:22674): GLib-GObject-CRITICAL **: 11:24:20.029: g_signal_emit_valist: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(io.elementary.videos:22674): Clutter-CRITICAL **: 11:24:20.029: clutter_content_invalidate: assertion 'CLUTTER_IS_CONTENT (content)' failed

(io.elementary.videos:22674): Clutter-CRITICAL **: 11:24:20.797: clutter_content_invalidate: assertion 'CLUTTER_IS_CONTENT (content)' failed
```
And it keeps looping 

> Clutter-CRITICAL.

ElementaryOS 
5.1 Hera
Ryzen 7 1800X
Radeon RX Vega 64

I'm using the latest released stable version of videos.

**Comment by danirabbit** [comment]
Closing since this is from before we started shipping Videos as flatpak and before GTK4 so the performance and codec situation is very different
