### ISSUE TITLE
Navigating back-and-forth on a video ends it immediately and returns

### ISSUE THREAD

**Issue by 3Nex** [elementary/videos#169]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

If i navigate to a video from the library, and then navigate back before the video finishes, then click the same video again, **i think** the player will try to remember the position where the video was left to keep playing from that position. But what happens is that the remembered position is (mistakenly) always at the very end, therefore the video will end immediately, on that second, and every subsequent play.

If a different video is played, then returning to the original video will no longer cause the issue.

Reproducible with .mkv and .avi files. Folder hierarchy seems irrelevant.

### To Reproduce
1. Browse videos from library
2. Click on a video
3. Navigate back before video finishes
4. Click on same video again

### Expected behavior
Video to play, either from start, or from last known position.

## Platform Information

 - OS: elementary OS
 - OS Version: elementary OS 5.1 Hera, Linux 5.0.0.-37-generic

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by AlbertAlonso** [comment]
I can confirm this.
