### ISSUE TITLE
Video Player Can't Play Video

### ISSUE THREAD

**Issue by Fatih20** [elementary/videos#170]
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug
Video can't be played with the app. The app simply display a blank screen. Video recording attached.

### Expected behavior
The video should've been played normally.

https://youtu.be/0pCBtpZUjp4

### Logs
```
(io.elementary.videos:22250): Gtk-DEBUG: 12:21:17.243: Connecting to session manager
** (io.elementary.videos:22250): DEBUG: 12:21:17.276: DiskManager.vala:111: Check DVD media for: Mass Storage
** (io.elementary.videos:22250): DEBUG: 12:21:17.276: DiskManager.vala:111: Check DVD media for: Fatih
** (io.elementary.videos:22250): DEBUG: 12:21:17.282: DiskManager.vala:111: Check DVD media for: Mass Storage
** (io.elementary.videos:22250): DEBUG: 12:21:17.282: DiskManager.vala:111: Check DVD media for: Fatih
** (io.elementary.videos:22250): DEBUG: 12:21:25.116: DiskManager.vala:111: Check DVD media for: Mass Storage
** (io.elementary.videos:22250): DEBUG: 12:21:25.117: DiskManager.vala:111: Check DVD media for: Fatih
** (io.elementary.videos:22250): DEBUG: 12:21:25.118: PlayerPage.vala:274: Opening file:///home/fatih/Videos/Anthony's%20Sponsor%20Spots/Linus%20Sponsor%20Spots.mp4
** (io.elementary.videos:22250): DEBUG: 12:21:25.123: Inhibitor.vala:64: Inhibiting screen
** (io.elementary.videos:22250): DEBUG: 12:21:25.123: DiskManager.vala:111: Check DVD media for: Mass Storage
** (io.elementary.videos:22250): DEBUG: 12:21:25.123: DiskManager.vala:111: Check DVD media for: Fatih
mesa: for the   --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the   --global-isel-abort option: may only occur zero or one times!
** (io.elementary.videos:22250): DEBUG: 12:21:37.175: Inhibitor.vala:80: Uninhibiting screen
** (io.elementary.videos:22250): DEBUG: 12:21:37.414: DiskManager.vala:111: Check DVD media for: Mass Storage
** (io.eleme
```

![image](https://user-images.githubusercontent.com/51940383/71501018-6868e180-289a-11ea-9f09-8e7eadd4e81b.png)

I'm using the latest released stable version

**Comment by JohnDumpling** [comment]
Videos still can't be played with the Video app. After opening any video file (.mp4 here), just a blank black screen appears:
![image](https://user-images.githubusercontent.com/89086803/130423044-50d0e2ed-c30c-4cb8-a17d-92a01b5bbd5a.png)

I am using Lenovo Legion 5 with elementary OS 6 (dualbooting Windows 10)
CPU: AMD Ryzen 4800h + Radeon iGPU
dGPU: nVidia GTX 1660ti mobile with 470 driver from AppCenter
Video app version 2.7.3

**Comment by JohnDumpling** [comment]
Update: When I play a video in VLC, it works fine. But when I press left/right arrow, a black screen appears but audio continues to play. This also happens when I maximize the video player.

**Comment by JohnDumpling** [comment]
From a Reddit post on Elementary OS subreddit:

    I read in some post that for the videos to work properly you might need to install extra multimedia codecs. Something about them being proprietary is why they aren’t installed by default.

    try sudo apt install ubuntu-restricted-extras

    and play some videos after to see if it works

For me, that worked. VLC has a different problem, it runs in 2 separate windows and every time I skip to a different part of a video, the blank window gets selected.

**Comment by lfvalerio** [comment]
> From a Reddit post on Elementary OS subreddit:
> 
> ```
> I read in some post that for the videos to work properly you might need to install extra multimedia codecs. Something about them being proprietary is why they aren’t installed by default.
> 
> try sudo apt install ubuntu-restricted-extras
> 
> and play some videos after to see if it works
> ```
> 
> For me, that worked. VLC has a different problem, it runs in 2 separate windows and every time I skip to a different part of a video, the blank window gets selected.

Completely worked for me as well! If these are not shipped by default because of legal restrictions we should have at least an easily accessible documentation or a "help" session on the video player, otherwise it's unusable, mp4 is used everywhere nowadays.
