### ISSUE TITLE
Videos crash when trying to open any video file

### ISSUE THREAD

**Issue by ECFE** [elementary/videos#192]
Opening any video file with the Elementary os videos application leads to a crash. The same files work fine with e.g. VLC. 

Error  message issued if videos is opened through the console:
Gdk-Message: 09:51:26.760: io.elementary.videos: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

OS version: elementary OS 5.1.3 Hera
Hardware: Dell Latitude E5540

**Comment by danirabbit** [comment]
Closing since this is a very old issue and no longer occurs
