### ISSUE TITLE
Provide UI for library control

### ISSUE THREAD

**Issue by jeremypw** [elementary/videos#194]
I have searched open and closed issues for duplicates.

## Feature
Currently, the only way to set the library folder location is by editing the settings using the commandline or dconf-editor - which is not "elementary". 

**Describe the solution you'd like**
Something similar to the other elementary media apps Music and Photos would provide consistency across elementary native media apps.  But that could be achieved incrementally.

**Existing work**
Music and Photos provide an AppMenu button offering "Import to Library" and "Preference" options. The "Preferences" dialog includes an option to set the library location.

**Describe alternatives you've considered**
The option could only be available on the Library page rather than the HeaderBar. e.g. through a context menu on the backgtound or on through a toolbar at the bottom (like the PlayerPage).

**Comment by danrabbit** [comment]
I kind of wonder if we should set XDG directories in System Settings -> applications or something instead. It seems like this could probably be more of a global setting.

@cassidyjames ?

**Comment by jeremypw** [comment]
Yes, that would be another way of achieving consistency between the media apps in this respect (if that setting is removed from all three).  Possibly they could ultimately share a media library control library?

**Comment by j60tt0** [comment]
At the moment the library is just a single path, would it be consistent with the elementary approach to allow this to be a collection of paths? Then the default could be something like, {"~/Videos", "/media/"} and importing would be adding to this collection? Or do you envisage that the import should be to a catalogue so that individual files/episode directores would be explicitly referenced and it could in theory be combined with the more detailed progress/resume timings that was listed as a separate feature request?

**Comment by jeremypw** [comment]
For discoverability I think there should be some link in Videos (and other media apps) that leads to the application settings plug. In the same that wingpanel indicators have a settings link.

**Comment by cassidyjames** [comment]
I feel like XDG directories should just be managed by the system… there is already logic in Ubuntu for changing the directories to translated versions when changing your language, and adding more layers on top of that seems problematic. I personally just feel like the Videos app should treat the XDG videos directory as its library location—same with Music and other apps. Trying to let the user point their XDG directory at some other location just seems like opening up all sorts of issues…

**Comment by danirabbit** [comment]
I'm going to close this because especially in Flatpak relocating the videos library causes issues
