### ISSUE TITLE
Videos does not present on Odin and can't launch

### ISSUE THREAD

**Issue by ryonakano** [elementary/videos#209]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
Videos is installed but does not present in Applications Menu, so it's not possible to launch the app―even from Terminal.

```
ryo@ryo-pc:~/Projects$ LANG=C apt-cache policy io.elementary.videos 
io.elementary.videos:
  Installed: 2.7.2+r1106-0+pkg49~daily~ubuntu6.0.1
  Candidate: 2.7.2+r1106-0+pkg49~daily~ubuntu6.0.1
  Version table:
 *** 2.7.2+r1106-0+pkg49~daily~ubuntu6.0.1 500
        500 http://ppa.launchpad.net/elementary-os/daily/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

### To Reproduce
* Open Applications Menu and you'll see Videos is not listed
* Open Terminal and try to run `io.elementary.videos`. It says there is no such a command

### Expected behavior
Videos should be listed in Applications Menu, and it's possible to launch from there or Terminal.

## Platform Information
I made a ISO using the scripts in the os repository today and installed Odin Daily using it.

- [x] I'm using the latest version from daily
- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

## Additional context
N/A

**Comment by ryonakano** [comment]
Seems like Launchpad [fails to build](https://code.launchpad.net/~elementary-os/+recipe/videos-daily):

```
dh_install: warning: Cannot find (any matches for) "usr/share" (tried in ., debian/tmp)

dh_install: warning: io.elementary.videos missing files: usr/share
dh_install: warning: Cannot find (any matches for) "usr/bin" (tried in ., debian/tmp)

dh_install: warning: io.elementary.videos missing files: usr/bin
dh_install: error: missing files, aborting
make: *** [debian/rules:17: binary] Error 25
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
```

I tried to create a .deb file on my local and also face the same error, so some file in deb-packaging branch may have the cause.

**Comment by danrabbit** [comment]
@ryonakano looks like we had a successful build 2020-08-25. Is this fixed now?

**Comment by ryonakano** [comment]
Yes, I tried `sudo apt install --reinstall io.elementary.videos` just now and it came back. Thank you for fixing this!
