### ISSUE TITLE
Adding AV1 support.

### ISSUE THREAD

**Issue by itskarudo** [elementary/videos#211]
## AV1 support.
AV1 is a relatively new video CODEC designed for web streaming, currently supported in a few apps.

I use elementary videos as my main video player but recently I couldn't manage to play AV1 videos due to the lack of the CODEC support where it only plays audio with black screen.

Adding AV1 support with something like [dav1d](https://www.videolan.org/projects/dav1d.html) would be a really great feature for the player and would allow a new range of videos to be played without the need of any external video player.

Programs that include AV1 support: VLC 3.0+, FFMPEG 4.0+, Mozilla Firefox 63+.

**Comment by tintou** [comment]
We are using GStreamer as underlying technology, if GStreamer supports AV1, so do we :slightly_smiling_face:

**Comment by tintou** [comment]
AV1 is already supported by GStreamer in the ["bad" plugins set](https://gstreamer.freedesktop.org/documentation/aom/av1dec.html), it should be available in next elementary OS major version
