### ISSUE TITLE
No sound when Play Video Elementary OS 5.1.7 But Avialable when test sound and ply musics

### ISSUE THREAD

**Issue by yadi2019** [elementary/videos#224]
sound avialable when i test sound, and play music
but no sound when play video
My pc is Acer Aspire C22-860
![Screenshot from 2021-06-03 21-30-49](https://user-images.githubusercontent.com/60699352/120645517-7bcaa400-c4b3-11eb-9c5f-c173a9bd1356.png)

**Comment by danirabbit** [comment]
Closing since this is from before we started shipping Videos as Flatpak and the codec situation is very different now. This should be resolved
