### ISSUE TITLE
Odin 6.0 No videos play

### ISSUE THREAD

**Issue by selwynorren** [elementary/videos#226]
## What Happened
So After installing Odin 6.0 Beta 2 and ran all updates, today 20th June 2021)  was the first chance I got to watch a video. Nothing plays at all. I can double click to open the mp4 video, however not progress bar, no video and no audio at all.

I launched video's form command line to see if any error show and nothing shows at all

## Expected Behavior
Video should play

## Steps to Reproduce
Try and play a standard mp4 video, or any video for that matter.

### Logs
Tried running using io.elementary.videos however nothing shows up and no error codes

## Platform Information
Elementary OS 6 Odin Beta 2 with all updates installed

I am curious if I need to install Ubuntu-restricted-extras or something else for videos to play? Also not sure if this is relevant, however if I connect to my plex server using Epiphany, then that plays in the browser no issues.

**Comment by davidmhewitt** [comment]
It's likely that you're missing the codec required to play that particular file. MP4 is just a container for media of some arbitrary codec, so an mp4 could be H.264 inside which is proprietary and doesn't have a decoder installed by default, or it could be some open source codec that would work out the box.

I had been working on some stuff to detect missing codecs and have AppCenter offer to install them but I never finished it and then I think someone decided it wouldn't be suitable in the world of everything being a Flatpak anyway.

As for solving your issue, definitely try installing restricted extras and see if that helps. I think it should pull in the "ugly" set of gstreamer plugins and maybe some ffmpeg libav stuff. It's one of those that'll probably make it work.

**Comment by matagyula** [comment]
I was about to respond by saying "same here", but all of a sudden videos are playing fine, and I am not sure what I changed :x I installed VLC, but that had no effect on the Video player. Other than that, I installed Microsoft Teams, and the VMWare Horizon Client.

I searched for installed packages and filtered by "ffm", "gst" and "libav":

```shell
libffmpegthumbnailer4v5/focal,now 2.1.1-0.2build2 amd64 [installed,automatic]

gir1.2-gstreamer-1.0/focal,now 1.16.2-2 amd64 [installed,automatic]
gstreamer1.0-alsa/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
gstreamer1.0-gl/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
gstreamer1.0-libav/focal,now 1.16.2-2 amd64 [installed,automatic]
gstreamer1.0-packagekit/focal-updates,now 1.1.13-2ubuntu1.1 amd64 [installed,automatic]
gstreamer1.0-plugins-base-apps/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
gstreamer1.0-plugins-base/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
gstreamer1.0-plugins-good/focal-updates,now 1.16.2-1ubuntu2.1 amd64 [installed,automatic]
gstreamer1.0-pulseaudio/focal-updates,now 1.16.2-1ubuntu2.1 amd64 [installed,automatic]
gstreamer1.0-tools/focal,now 1.16.2-2 amd64 [installed,automatic]
gstreamer1.0-x/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
libclutter-gst-3.0-0/focal,now 3.0.27-1 amd64 [installed,automatic]
libgstreamer-gl1.0-0/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
libgstreamer-plugins-base1.0-0/focal-updates,now 1.16.2-4ubuntu0.1 amd64 [installed,automatic]
libgstreamer-plugins-good1.0-0/focal-updates,now 1.16.2-1ubuntu2.1 amd64 [installed,automatic]
libgstreamer1.0-0/focal,now 1.16.2-2 amd64 [installed,automatic]

gstreamer1.0-libav/focal,now 1.16.2-2 amd64 [installed,automatic]
libavahi-client3/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
libavahi-common-data/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
libavahi-common3/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
libavahi-core7/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
libavahi-glib1/focal,now 0.7-4ubuntu7 amd64 [installed,automatic]
libavc1394-0/focal,now 0.5.4-5 amd64 [installed,automatic]
libavcodec58/focal-updates,now 7:4.2.4-1ubuntu0.1 amd64 [installed,automatic]
libavfilter7/focal-updates,now 7:4.2.4-1ubuntu0.1 amd64 [installed,automatic]
libavformat58/focal-updates,now 7:4.2.4-1ubuntu0.1 amd64 [installed,automatic]
libavutil56/focal-updates,now 7:4.2.4-1ubuntu0.1 amd64 [installed,automatic]
```

Do you happen to have these ones as well?

**Comment by selwynorren** [comment]
Howdy, sop installing Ubuntu-restriced-extras did the trick for me. Once this was installed, all the relevant codecs were installed as well.

I was just surprised that no video played out of the box.

**Comment by davidmhewitt** [comment]
I'll close this issue, since there are other more specific issues/PRs open about the fact that there isn't a checkbox anywhere to just install the proprietary codecs at some point and that videos doesn't tell you that it's missing codecs.

See https://github.com/elementary/initial-setup/pull/92, https://github.com/elementary/videos/issues/97 , https://github.com/elementary/appcenter/issues/623
