### ISSUE TITLE
Odin: Does not play anything

### ISSUE THREAD

**Issue by marbetschar** [elementary/videos#229]
## What Happened

The app does no play anything on my bare metal installation (Dell XPS 7390). Whenever I open a file in Files, the Videos app starts but the area where the video is supposed to play stays black. Nothing happens as well when I click the play button.

All the files I tested run just fine in VLC.

Running the latest daily (elementary 6).

## Expected Behavior

The video should be displayed and autoplay when opened from Files.

## Steps to Reproduce

Just try to open any video file (*.mp4)

**Comment by davidmhewitt** [comment]
Something like #226?

**Comment by marbetschar** [comment]
thanks @davidmhewitt! yes, its exactly like #226. Executing the following command fixed the issue:

```
sudo apt install ubuntu-restricted-extras
```

Would be nice if the app informs about missing codecs. I've seen this is already discussed in https://github.com/elementary/videos/issues/97 so I'm closing this.
