### ISSUE TITLE
videos missing rounded window corners 

### ISSUE THREAD

**Issue by eric0001** [elementary/videos#232]
In elementary OS 6 Beta 2, unlike all the other default applications (e.g. camera), videos does not have rounded window corners.
![videos-missing-rounded-window-corners](https://user-images.githubusercontent.com/39679934/126484009-2199a77d-6995-4615-953e-8b8347016b2a.png)
![camera-has-rounded-window-corners](https://user-images.githubusercontent.com/39679934/126484029-e9a2502d-1b23-4d6f-b778-9dcacdc805b9.png)

**Comment by danrabbit** [comment]
Videos is still using Clutter.Gst currently, so it will need to be ported to the native Gtk elements for Gstreamer the same as was done for Camera here: https://github.com/elementary/camera/commit/a5c08d818dac9cf6c9236a7ce102edee35e13917

Once that's done, we can use Hdy.Window here

**Comment by eric0001** [comment]
I'm happy that this issue will be addressed. Thank you for the explanations. :-)
