### ISSUE TITLE
Mouse cursor disappears, but does not reappear after moving the mouse

### ISSUE THREAD

**Issue by JohnDumpling** [elementary/videos#235]
## What Happened
When trying to play a video file and leaving the mouse cursor intact, it automatically disappears along with the bottom video playback controls (which is fine and is intended behavior). But when I move the cursor again, it does not reappear and video controls neither. Cursor appears again after it leaves the area of the app window.
![image](https://user-images.githubusercontent.com/89086803/130424715-20ce4b99-a11c-49c4-a05b-54380e0cbda4.png)
This issue may be related to [#170](https://github.com/elementary/videos/issues/170) - as I have the same problem in combination with this secondary issue.

## Expected Behavior
1. (Working) When not moving the mouse cursor inside the Video window, after a couple of seconds the cursor should disappear.
2. When I move with the mouse again, the cursor should reappear along with video playback controls on the bottom.

## Steps to Reproduce
1. Open a video file inside Video app
2. Move the cursor inside a paused video and wait until it disappears
3. Move the cursor again and observe, whether it reappears

## Platform Information
Lenovo Legion 5 running elementary OS 6 (dualbooting Windows 10)
CPU: Ryzen 4800h + Radeon iGPU
dGPU: GTX 1660ti mobile with nVidia 470 driver from the AppCenter
App version: 2.7.3

**Comment by JohnDumpling** [comment]
Yep, it was connected to the #170 issue, closing this one.

**Comment by verachlvfn-rgb** [comment]
[video_20251109_162739_020000076.mp3](https://github.com/user-attachments/files/24360745/video_20251109_162739_020000076.mp3)
