### ISSUE TITLE
Unable to play any Videos [Odin 6]

### ISSUE THREAD

**Issue by kem-a** [elementary/videos#237]
Kinda denies existence of this app. I would love to help, but I couldn't generate any logs.
To reproduce I just tried to play any video, but nothing happens, app has black screen. App reacts and can be closed.
Tried H.264 and H.265 format. The same videos play perfectly well on other apps (deb packages). Tried MPV and VLC.
Tried also to purge and reinstall without success.

App: `io.elementary.videos/focal,now 2.7.3+r1175+pkg52~ubuntu6.1 amd64 [installed]`
Used Intel GPU as well nVidia with no difference.

```bash
OS: elementary OS 6 Odin x86_64 
Host: Aspire VX5-591G V1.08 
Kernel: 5.11.0-27-generic 
```

**Issue**: [Missing codecs, GStreamer](https://github.com/elementary/videos/issues/237#issuecomment-912764439)

**Comment by JohnDumpling** [comment]
From a Reddit post on Elementary OS subreddit:

> I read in some post that for the videos to work properly you might need to install extra multimedia codecs. Something about them being proprietary is why they aren’t installed by default.
> 
> try sudo apt install ubuntu-restricted-extras
> 
> and play some videos after to see if it works

For me, that worked.

**Comment by vf8bullet** [comment]
![Screenshot from 2021-09-03 00 38 10](https://user-images.githubusercontent.com/79075579/131883233-a54ccfe4-d20c-4e1a-b71e-25cae5c27875.png)

garbled videos on mine

**Comment by kmandarin-orange** [comment]
For me it was what @JohnDumpling said, I needed to install the codecs, after that things worked fine. I wonder if there should be a short splash text on open that can warn users they don't have the right codecs installed and where to get them. Implementing that cleanly might not be easy but I think it's helpful enough to consider.

**Comment by AI-ien** [comment]
Okey, installing 'ubuntu-restricted-extras' solved the issue. So problem truly lies within missing codecs. I doubt that it is some propriety issues, otherwise all video players would be useless. It more looks that devs forgot to pack those codecs, but its just my guess.

**Comment by jeremypw** [comment]
The real issue is not so much do some videos do not play; there will likely always be some formats that will not play oob for legal reasons if nothing else.  The issue is that Videos does not fail gracefully and provide useful information to the user.  

See #97 and #155 for possible a fix.  There are number of similar issues already raised.

@davidmhewitt You were working on #155 at one point; will you be able to make progress at some point? I know you are concentrating on flatpak and other issues atm.

**Comment by jeremypw** [comment]
Might also be worth an audit of whether elementaryos is supplying all the codecs that it could, legally.

**Comment by davidmhewitt** [comment]
I stopped working on it when someone (I think in Slack) mentioned that the solution I was proposing doesn't make sense in the context of porting things to Flatpaks, so I lost motivation and stopped work at that point.

Then Videos never got shipped as a Flatpak 🤷‍♂️

**Comment by davidmhewitt** [comment]
This is the relevant branch for AppCenter that works in conjunction with #155 : https://github.com/elementary/appcenter/pull/1419

It would probably be nicer if the changes were ported to use the new notifications with action buttons rather than using dialogs, but the AppCenter branch wasn't that close to finished yet anyway. I proved that the concept would work, but never finished the implementation.

**Comment by jeremypw** [comment]
@davidmhewitt Thanks for the update.  Is there any technical reason that Videos cannot be Flatpak'd? If not I guess it will be eventually so any solution will have to be Flatpak compatible.

**Comment by davidmhewitt** [comment]
I don't think there's a technical reason, but there might have been some legal discussion around that too. 

I can't remember if it would be possible to pull the proprietary codec extensions from flathub, like we do for things like the OpenGL runtime, or if they'd have to be hosted on the elementary remote as an extension of the elementary runtime. 

And then elementary would be a H.264 codec distributor, and with elementary being a US company, they'd fall under that patent law and have fees payable.

Either way, the branch I was beginning to propose for AppCenter would notify and offer to install codecs for any Gstreamer application that had missing codecs that was running outside of a sandbox. But I don't have a lot of interest in working on it now.

**Comment by jeremypw** [comment]
Yeah, sounds like a potential can of worms.  Needs UX team input as to the appropriate course of action.  I would think that, at a minimum, some informative message should be displayed even if the needed codecs cannot be installed from within the app.

**Comment by JohnDumpling** [comment]
When I reinstalled elementary OS 6 yesterday and tried to play an .avi video, sound worked but the screen remained black. Surprisingly, .mp4 worked well. Installing missing codecs using the previously mentioned `sudo apt install ubuntu-restricted-extras` didn't seem to solve the issue.

**Comment by jeremypw** [comment]
@JohnDumpling I think the problem is that when running in a Flatpak you need to install the appropriate Flatpak extension, not the deb package. See #285 for pending fix.

**Comment by SubhadeepJasu** [comment]
Artem Anufrij's Cinema works fine for me. May be take a look at what he's doing?

**Comment by danirabbit** [comment]
Seems like this issue report comes from before we started shipping Videos as Flatpak. Things are all resolved now :)
