### ISSUE TITLE
garbled videos

### ISSUE THREAD

**Issue by Radical4ever** [elementary/videos#238]
This happens to me since hera and some mp4 videos make this behaviour, mkv works fine
![Captura de pantalla de 2021-09-14 06-51-54](https://user-images.githubusercontent.com/83252104/133236827-c775dc2a-9eb7-4cd4-b44f-9b487e56af74.png)
and i have all the codecs installed as other issues says

**Comment by vf8bullet** [comment]
https://github.com/elementary/videos/issues/237#issuecomment-911868164

same

**Comment by Radical4ever** [comment]
i guess i'm not the only one

**Comment by AlwynBarry** [comment]
Me too!  In fact all mp4 videos are like this, and also the few webm files I have.  But they all play OK in VLC.  Why not in the Videos App then??  I've a 12Glaptop with Intel graphics.

**Comment by cisordeng** [comment]
Hello @Radical4ever @vf8bullet @AlwynBarry , the same problem, I solved it this way

```
sudo apt install ubuntu-restricted-extras
sudo apt remove ubuntu-restricted-extras
sudo apt autoremove
```

**Comment by Radical4ever** [comment]
> Hello @Radical4ever @vf8bullet @AlwynBarry , the same problem, I solved it this way
> 
> ```
> sudo apt install ubuntu-restricted-extras
> sudo apt remove ubuntu-restricted-extras
> sudo apt autoremove
> ```
> 
> This works for me, hope it can help you~

sadly that didnt help me and the brand new flatpak videos works fine but slow, the only cool video player i could find is totem
