### ISSUE TITLE
Calling org.freedesktop.portal.Inhibit.Inhibit failed

### ISSUE THREAD

**Issue by danirabbit** [elementary/videos#241]
### What Happened?

I have some Terminal output that the inhibit interface was unable to be called

### Steps to Reproduce

1. Install Videos from flatpak
2. Run from Terminal
3. Play a video

### Expected Behavior

Inhibit portal should be available. I'm wondering if this is because I'm running the elementary portals package and there's something there that's overriding one of the other portals?

### OS Version

6.x (Odin)

### Software Version

Compiled from git

### Log Output

```shell
GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop
```

**Comment by Marukesu** [comment]
I cannot reproduce it here, no warning is shown, and bustler show the calls to the portal as expected. Also have the elementary portals installed.

My portals versions:
```
$ /usr/libexec/xdg-desktop-portal-gtk --version
xdg-desktop-portal-gtk 1.7.1
$ /usr/libexec/xdg-desktop-portal --version 
xdg-desktop-portal 1.7.2
```
