### ISSUE TITLE
No thumbnails in Flatpak

### ISSUE THREAD

**Issue by danrabbit** [elementary/videos#243]
### What Happened?

I'm not getting any Thumbnails in the flatpak, it just spins and spins

### Steps to Reproduce

1. Install videos as flatpak
2. Open the library to see stuff you have in home/videos
3. See the spinner spin

### Expected Behavior

The spinner should eventually stop and give us thumbnails

### OS Version

6.x (Odin)

### Software Version

Compiled from git

**Comment by Marukesu** [comment]
videos is using `Environment.get_user_cache_dir ()` to get the thumbinail cache, however, inside the sandbox that's `/var/cache` but the thumbnails is on the host cache, in `/home/$USER/.cache`
