### ISSUE TITLE
The "Suggest Translation" button is pointing to the wrong link

### ISSUE THREAD

**Issue by GabrielMGitHub** [elementary/videos#26]
The "Suggest Translation" button is pointing to the wrong link. This error has several applications.
https://translations.launchpad.net/audience

![captura de tela de 2017-05-27 14-26-53](https://cloud.githubusercontent.com/assets/8754997/26523188/8b6cd208-42e8-11e7-8c51-8338aafd3e40.png)

**Comment by Spiritus44** [comment]
I think the good link is :
https://l10n.elementary.io/projects/videos/

Can you confirm ?

**Comment by leonardo-lemos** [comment]
Solved in #22
