### ISSUE TITLE
Minimal Videos

### ISSUE THREAD

**Issue by kdwk** [elementary/videos#276]
### Problem

The title bar and black bars around the video cannot be hidden in floating window mode.

### Proposal

Provide a (automatic?) way to just view the video. Make the window exactly as big as the video and hide everything that is not the video, including title bar and black bars. Perhaps this view can be made the default every time a video is opened, and the extra title bars and controls can appear when the mouse cursor hovers and moves over the video.

### Prior Art (Optional)

Minimal Camera proposed here: https://github.com/elementary/camera/pull/125

macOS video player (I don’t have access to macOS so this is iPadOS PiP mode, but they look very similar): 
![41BAED16-B19F-42DA-A413-3E1A4C70EFB5](https://user-images.githubusercontent.com/39268094/138980408-6b583c01-552a-4481-a03a-220f1278ce0f.png)

**Comment by danirabbit** [comment]
Fixed in #382
