### ISSUE TITLE
Cannot play mkv or mp4 videos

### ISSUE THREAD

**Issue by aspizu** [elementary/videos#314]
### What Happened?

video is blank 
audio is fine
cant play any videos
i have installed ubuntu-restricted-packages

### Steps to Reproduce

play video

### Expected Behavior

video should play

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by theoteno** [comment]
Is it the flatpak version, maybe?
That might help a bit, but I didn't used the default video player on Elementary that much . . .

**Comment by aspizu** [comment]
the one which comes with odin

**Comment by theoteno** [comment]
It's probably flatpak, but I don't know what breaked the video playback. (drivers, etc.)

I'd recommend to build videos2, or Cinema(playmyvideos) from source code: it's actually well documented how to do it, both players are written in Vala & look very similar designwise.

Maybe even Celluloid would look great in elementary theme, and you don't need to compile & build that app.

**Comment by danirabbit** [comment]
With the latest videos on OS 8, I'm able to play mkv and mp4 videos. I'm guessing this is maybe an issue due to an older release or a mismatched version of codecs. This should be solved now that we're shipping Flathub and the current runtimes should stay up to date automatically

**Comment by robot3human0** [comment]
> With the latest videos on OS 8, I'm able to play mkv and mp4 videos. I'm guessing this is maybe an issue due to an older release or a mismatched version of codecs. This should be solved now that we're shipping Flathub and the current runtimes should stay up to date automatically

Actualy it stilll doesn't play any video, only audio, just intstall this os and all codecs. another app play video just out of the box.

**Comment by jeremypw** [comment]
Update I could not get MP4 videos to play in EOS8.1 apart from the sound (nor in the pre-release version of EOS9). Installed VLC from `.deb` and the restricted extras package.  Made no different to Videos although VLC played the files OK.  Videos played `.avi` and `.mpeg` video files OK though.

**Comment by danirabbit** [comment]
@jeremypw flatpak apps don't use host codecs. Videos uses the codecs supplied in `org.freedesktop.Platform.codecs-extra`. It looks like Ryo updated those to the latest recently https://github.com/elementary/videos/pull/419

**Comment by jeremypw** [comment]
@danirabbit I have `org.freedesktop.Platform.codecs-extra 25.08` installed but Flatpak Videos still  plays MP4 audio only.  It would be good if Videos could give some user feedback about a missing codec issue.
