### ISSUE TITLE
No video (only audio) on video playback

### ISSUE THREAD

**Issue by TomiOhl** [elementary/videos#320]
### What Happened?

On version 2.9.1-3.0.0 (daily/main/stable branches):
- mp4 h264/h25, mkv: audio plays, no video

On version 2.9.0:
- mp4 h264 plays fine, but
- mp4 h265 show only black screen (audio is playing)
- mkv is playing but it stutters a lot

The issue looks pretty much the same as #281 looked like.
The `org.freedesktop.Platform.openh264` package is installed though. Installing `org.freedesktop.Platform.ffmpeg-full` manually doesn't help. All platform packages are installed from the same source to the user:
![image](https://github.com/elementary/videos/assets/6696659/d90b0dbc-1bb4-45c0-bff0-a808799afc9f)

### Steps to Reproduce

Tried to play different video formats

### Expected Behavior

Smooth playback

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
Gtk-Message: 01:27:18.468: Failed to load module "canberra-gtk-module"
Gtk-Message: 01:27:18.470: Failed to load module "canberra-gtk-module"

(io.elementary.videos:2): Gtk-WARNING **: 01:27:20.418: Negative content width -13 (allocation 1, extents 7x7) while allocating gadget (node actionbar, owner GtkActionBar)

(io.elementary.videos:2): GLib-GObject-WARNING **: 01:27:20.815: invalid unclassed pointer in cast to 'GstAudioRingBuffer'
```

### Hardware Info

HW1: Intel Core I5-8250U with Intel UHD Graphics 620 (Kabylake GT2)
HW2: AMD Ryzen 7 PRO 6850U with AMD Radeon 680M

**Comment by TomiOhl** [comment]
Same after updating to OS 7 (it's like this even on the installation media in live mode)

**Comment by TomiOhl** [comment]
Bumping this: same with videos 2.9.0 even on a freshly installed system on ThinkPad T16 AMD. After updating to version 2.9.1, there's no video at all, only sound.

**Comment by TomiOhl** [comment]
Additional info: the fourth line from the log doesn't appear in v2.9.1. But those logs don't seem to be related anyways.

**Comment by TomiOhl** [comment]
Note that manually installing `org.freedesktop.Platform.ffmpeg-full` doesn't help.

**Comment by hexerus** [comment]
Same issue.

Flatpak: io.elementary.videos
Version: 2.9.1
Branch: daily
Mesa and Mesa (extra) version 22.08 installed as flatpaks.
Intel VAAPI 22.08 installed as flatpak.
ubuntu-restricted-extras installed from apt.

Can only hear sound on mp4 (h264 or h265). Cannot see video.

Celluloid works just fine (flatpak).

**Comment by TomiOhl** [comment]
I'm using mpv (flatpak) which also works just fine without pulling in any additional platform dependencies. Here is what I have installed (besides Elementary Platform 7.2 and random apps):
![image](https://github.com/elementary/videos/assets/6696659/663b7d38-298b-440c-809f-fae47a3775c3)

**Comment by hexerus** [comment]
Yeah.. anything decent that either comes bundled with its own codecs, installs the missing codecs as dependencies on its own OR notifies the user about those missing codecs (free/proprietary) required to play the file would work as expected. Like VLC, mpv (and its various frontends) etc.

**Comment by TomiOhl** [comment]
Same issue with 3.0.0

**Comment by lenemter** [comment]
@TomiOhl What video are you trying to play? I just downloaded a random video from YouTube and Videos managed to play it.

**Comment by Marukesu** [comment]
Also tried two MP4 samples (h264/h265) here, both worked fine.

**Comment by TomiOhl** [comment]
Since then I've tried reinstalling the extension to the system: 
![image](https://github.com/elementary/videos/assets/6696659/342e87ae-3a2e-4db9-9949-80979a3b9bbc)


Running the given command yiels results: 
![image](https://github.com/elementary/videos/assets/6696659/2061dc87-fb11-4783-b9ca-28114fe5a2c1)

**Comment by TomiOhl** [comment]
> @TomiOhl What video are you trying to play? I just downloaded a random video from YouTube and Videos managed to play it.

Basically any video I try, but here's a sample:
https://github.com/elementary/videos/assets/6696659/e510f86b-8360-466f-8b91-d0b26ec1ec39

I have to stress that I have the same issue even when booting the os from a live usb.

Some related info from more users: https://www.reddit.com/r/elementaryos/comments/152h6au/are_any_special_actions_needed_to_be_able_to_use/

**Comment by TomiOhl** [comment]
Breaking: either one of these solved the issue, videos play fine now! Ngl I'm scared to change anything now, would be better to experiment on a live usb, but I have formatted mine so leaving this task for later

**Comment by TomiOhl** [comment]
So openh264 from branch 2.2.0 is indeed what does the trick. Tried uninstalling it on my other laptop. No video after it, but immediately got a notification from AppCenter for an update that installed it back. Video playback works fine again after that, although a bit choppy, but that's probably unrelated as I don't have this issue on my other laptop.
Not sure what changed, why did this issue got randomly fixed for me on two devices at the same time after 8 months, but I guess it's time to close the issue 🎉
