### ISSUE TITLE
Subtitles disappear on audio track change

### ISSUE THREAD

**Issue by danielnd14** [elementary/videos#35]
When i try to play videos that have subtitles in separated .srt files that have the same name as the video, the player shows it as expected, but when I click on the cog button to change the audio track the subtitles disappear.

**Comment by peteruithoven** [comment]
I'd love an example file for this one. 
I did notice there might be some audio track related code that look at subtitles where it shouldn't: https://github.com/elementary/videos/blob/master/src/Widgets/Player/SettingsPopover.vala#L133-L152
