### ISSUE TITLE
Video is playing in own window

### ISSUE THREAD

**Issue by zeebok** [elementary/videos#390]
### What Happened?

When opening an MP4 file it creates a new window with the video. Controls still work, though moving the cursor over the timeline causes preview images in new windows as well (seems to be a related issue)  and will hide away as seen in this screen shot:

![Screenshot from 2024-08-01 01 39 57](https://github.com/user-attachments/assets/407e63c3-f230-4b6c-ba73-fe6b5404b7d2)

### Steps to Reproduce

1. Open a video

### Expected Behavior

The video plays within the app's window

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by leolost2605** [comment]
Probably same as #356. Have you installed it as flatpak or native?

**Comment by TomiOhl** [comment]
Same here: upgraded the official installation from appcenter (flatpak)

**Comment by zeebok** [comment]
It is the flatpak. I haven't touched the app since installing besides updates
