### ISSUE TITLE
Subtitle disconnected with keyboard jump

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/videos#43]
Hi.
Jumping back and forth the video using left and right keys disconnects the subtitle file while using the mouse does not.

**Comment by arshubham** [comment]
@WebShapedBiz After a lot of tries, I am still unable to reproduce it. Can you share a sample video and subtitles for reproduction?  Might have been fixed in the underlying libraries along the way.

**Comment by WebShapedBiz** [comment]
Thank you @arshubham for this, but this was in August 2017. and I'm not using the same eOS version to be able to reproduce it for you. As I can remember, as soon as you start jumping up and down the video, with your mouse or keyboard, the subtitles went out of sync or disappeared altogether.

**Comment by arshubham** [comment]
@WebShapedBiz Can you reproduce it in latest version? Most of these issues have nothing to be Videos itself, but are in gstreamer or gst.

**Comment by WebShapedBiz** [comment]
Yes, I just did that. Now it works fine.

**Comment by arshubham** [comment]
Thanks. So I will close this. You can always open a new issue, but please remember to attach a sample file for debugging.
