### ISSUE TITLE
Change package name to io.elementary.videos

### ISSUE THREAD

**Issue by waldyrious** [elementary/videos#45]
I'm not sure if this is being tracked elsewhere, but I couldn't find any issues in this repo referring to this. I believe there was a blog post about this subject (older than [the one about using RNN](https://medium.com/elementaryos/cleaning-up-app-codenames-ef9fc637ddef), but I may be mistaken.)

My question is whether it makes sense (or is planned) for this app's .deb package (i.e. as it appears in `apt`) to be named `audience-video-player`, just like e.g. [elementary/scratch](https://github.com/elementary/scratch) is named `scratch-text-editor` and [elementary/calendar](https://github.com/elementary/calendar) is named `maya-calendar`, and so on.

I am sure this has already been discussed, in which case this issue may be moot; pointers to where this information could be found would be appreciated.

**Comment by Ghostboy-287** [comment]
i did `apt list --installed` and i searched for the word `video` to check the name of the elementary video player but didn't find anything 
so i had to search on google to find that its name is `audience `
( it could have been a little more popular if it had a tag word like `video-player` )

**Comment by danrabbit** [comment]
I think in the future it will probably be `io.elementary.videos`

**Comment by seesemichaelj** [comment]
@danrabbit I'm fairly certain this is complete and can be closed

**Comment by waldyrious** [comment]
@seesemichaelj I wouldn't say so. Per @mIcHyAmRaNe's comment:

```
$ apt list --installed | grep audience
[...]
audience/bionic,now 2.7.0+r990+pkg46~ubuntu5.0.1 amd64 [installed,automatic] 
```

compare e.g. with the `code` package (previously the scratch editor):

```
$ apt list --installed | grep code
[...]
io.elementary.code/bionic,now 3.1.1~r2719+pkg126~ubuntu5.0.1 amd64 [installed,automatic]
```

**Comment by seesemichaelj** [comment]
Ah, I didn't read the issue thoroughly to see you're specifically referring to what it's listed as in the PPA. You're right; it's still `audience`

For posterity's sake:

[packages released under `audience`](https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages?field.name_filter=audience&field.status_filter=published&field.series_filter=)

[packages released under `io.elementary.videos`](https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+packages?field.name_filter=io.elementary.videos&field.status_filter=published&field.series_filter=)

**Comment by danirabbit** [comment]
I think this is fixed https://github.com/elementary/videos/blob/deb-packaging/debian/control

**Comment by waldyrious** [comment]
Cool, so it looks like this was fixed by https://github.com/elementary/videos/pull/207. Thanks!
