### ISSUE TITLE
Full screen isn't full

### ISSUE THREAD

**Issue by Nomadjackalope** [elementary/videos#60]
It would seem that maximizing a video player would make it completely full-screen. This is typical as seen in Quicktime, VLC and other video players.

Is a non-full-screen player a purposeful decision or an issue with code?

**Comment by tintou** [comment]
This is a design decision
I wonder how do you watch videos maximized, the main target of the Desktop Environment is to allow you to stay focus on your work so if you have things moving behind the main window it will highly decrease you attention to that work

**Comment by Nomadjackalope** [comment]
I use elementary as my main os so I use it for work and play. Currently I watch full screen videos on a different Desktop in Multitasking View using VLC full screen. Sometimes I do this on a separate monitor.

**Comment by danrabbit** [comment]
OP can you clarify exactly what are the steps to reproduce the problem? I feel like there might be a bit of a miscommunication happening here. Are you saying that you're expecting a full screen window while using multi-tasking view? When exactly does the issue occur? Are you using a keyboard shortcut or window buttons? Could you clarify which is the behavior that is occurring and which is the behavior you are expecting?

**Comment by Nomadjackalope** [comment]
I am clicking on the window maximize button as shown here:
[https://i.imgur.com/m9xvjN7h.png?1](https://i.imgur.com/m9xvjN7h.png?1)

I am expecting something like this where the video opens full-screen to a new multitasking window:
[https://i.imgur.com/z4sWfFIh.png](https://i.imgur.com/z4sWfFIh.png)

But the window maximizes like any other program like this:
[https://i.imgur.com/tLsCo5qh.png](https://i.imgur.com/tLsCo5qh.png)

What actually happens is normal for any other program but it is weird to me that I can't get the video player to the expected. This results in watching a movie with bars sitting at the top.

Sorry for not being clear. This isn't an issue so much as a preference. It just seemed very odd to me. And, as a beginner to elementary development, it might be an issue I could help fix.

**Comment by danrabbit** [comment]
Ah okay, this was fixed here: https://github.com/elementary/videos/commit/515f0bd99d42821df33d42d0155e75e4cd6575ac

It now works as you'd expect in master :)

**Comment by Nomadjackalope** [comment]
Oh Thanks :)
