### ISSUE TITLE
there is a button connected with gala-pip

### ISSUE THREAD

**Issue by torikulhabib** [elementary/videos#61]
I hope there is a button connected with gala-pip.
just klick tool bar like youtube app on android.

**Comment by peteruithoven** [comment]
Could you clarify? Maybe add a graphic visualizing your idea?

**Comment by torikulhabib** [comment]
@peteruithoven maybe like that, or I think like the screenshot tool button - "grab the current window"
one click gala-pipe appear.

**Comment by peteruithoven** [comment]
I've opened the following 2 issues to increase the discoverability in a more general way:
https://github.com/elementary/applications-menu/issues/209
https://github.com/elementary/gala/issues/557
