### ISSUE TITLE
Fullscreen video tearing

### ISSUE THREAD

**Issue by mdh34** [elementary/videos#76]
In fullscreen mode I get video tearing (with proprietary nvidia drivers)

This might be linked to mutter / gala undirecting fullscreen windows so this might not be the right place for this bug

**Comment by arshubham** [comment]
@mdh34 Are you still experiencing this issue with latest drivers in juno?

**Comment by arshubham** [comment]
Closing since OP has not responded. Will reopen if the issue persists. It is most probably an issue with the drivers or mutter/gala and was first reported for Loki. Not much actionable here.
