### ISSUE TITLE
meson: don't install extra.mo files (regression)

### ISSUE THREAD

**Issue by decathorpe** [elementary/videos#92]
Commit https://github.com/elementary/videos/commit/2d0c2f8b6e2f9bdb5dc403bbb4a21dd8fa3267ac dropped the `install : false` flag in `po/extra/meson.build`, probably by accident.

**Comment by tintou** [comment]
Fixed now, thanks for watching closely

**Comment by decathorpe** [comment]
Thanks for fixing it so quickly :+1:
