### ISSUE TITLE
Video Gets Stuck and Audio continues

### ISSUE THREAD

**Issue by Pspfriends** [elementary/videos#93]
While Playing any videos video visual stucks after few seconds and there is no lag or stop in audio... when the cursor is moved video gets continued along with the audio ..

**Comment by ryonakano** [comment]
I'm facing this issue on Juno Beta1, with Videos 0.2.6

**Comment by vser** [comment]
This is also a problem I'm facing. VLC seems to work just fine but other videos when played in the Videos application or web browser (both built in and Google Chrome) seem to visually freeze when the cursor has stopped moving.

**Comment by joranrood** [comment]
The same problem seems to occur with GNOME Videos (3.26) but not with GNOME MPV (0.13) on Juno Beta 1. Could the problem be related to GStreamer, which is used by Videos and GNOME Videos?

**Comment by peteruithoven** [comment]
I think this issue covers the same and is more active: https://github.com/elementary/os/issues/121
Please correct me if I'm wrong.
