### ISSUE TITLE
Use gstreamer1.0-packagekit to offer missing codecs

### ISSUE THREAD

**Issue by codygarver** [elementary/videos#97]
In the past we used `gnome-codec-install` to ask for more codecs but it's dead now.

We're meant to be using `gstreamer1.0-packagekit` but it's not working with Videos for some reason. Missing support?

Right now elementary OS ships many codecs so no one has noticed there's no prompt anymore, that `sessioninstaller` (old solution) is broken.

**Comment by danrabbit** [comment]
@cassidyjames Any idea about how this works in GNOME? Is it maybe implemented in GNOME Shell or GNOME Software or something and we need to make an agent?

**Comment by cassidyjames** [comment]
@danrabbit I'm not sure. I think it would be Software and not Shell. I'd have to boot a VM up to check, though.

**Comment by jeremypw** [comment]
I noticed Videos failed to play some old MPG videos - could this be related?  VLC played them OK (and Files thumbnailed them).  Moreover, Videos failed to give any useful information - just a black screen and a video length of zero.

**Comment by danirabbit** [comment]
Gonna close this since it's no longer relevant to Flatpak
